require:
  - rubocop-rails
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.7.2
  NewCops: enable
  Exclude:
    - "assets/**/*"
    - "bin/**/*"
    - "db/schema.rb"
    - "log/**/*"
    - "node_modules/**/*"
    - "tmp/**/*"
    - "vendor/**/*"

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enable: false

Layout/LineLength:
  Max: 160

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/WordArray:
  Enable: false

Style/SymbolArray:
  Enable: false